### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptotools.BTC'

### ISSUE THREAD

**Issue by annu02909** [vlnahp/Btcbf#1]
C:\Users\amd\Btcbf>python Btcbf.py
Traceback (most recent call last):
  File "C:\Users\amd\Btcbf\Btcbf.py", line 7, in <module>
    from cryptotools.BTC import generate_keypair, push, script_to_address, OP
ModuleNotFoundError: No module named 'cryptotools.BTC'

i can't find this module cryptotools.BTC

**Comment by vlnahp** [comment]
This module is not available on PyPI, you have to install it manually.

>$ pip install git+https://github.com/mcdallas/cryptotools.git@master#egg=cryptotools (for Linux) (on windows download and install from GitHub manually: https://github.com/mcdallas/cryptotools )

On windows download this [link](https://github.com/mcdallas/cryptotools/archive/refs/heads/master.zip). Then navigate to the path where python is installed( use _>where.exe python_ command in cmd or PowerShell to find it). Go to _/lib/site-packages_ and extract the zip file downloaded before to this folder. Navigate to _/cryptotools-master_ , open PowerShell or cmd, execute _>python setup.py install_ command, and you are done!!

I used this module because of its speed. I have tried many modules and this was the fastest thanks to @mcdallas

**Comment by vlnahp** [comment]
Removed this dependency :white_check_mark:

**Comment by pbies** [comment]
On Mac M2 even if cryptotools installed for user and root (sudo) still the error remains the same. Seems like he does not find the folder with library.
